[package]
name = "simd-examples"
version = "0.1.0"
authors = ["Eric Berquist <eric.berquist@gmail.com>"]
edition = "2018"

[dependencies]
vsop87 = "2.0"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "simd_examples_bench"
harness = false
